export interface MockListing {
  id: string;
  title: string;
  location: string;
  distance: string;
  dates: string;
  price: number;
  rating: number;
  reviewCount: number;
  images: string[];
  trustScore: number;
  connectionLabel: string | null;
  isSuperhost: boolean;
  category: string;
}

export const mockListings: MockListing[] = [
  {
    id: "1",
    title: "Cozy Cabin in the Smoky Mountains",
    location: "Gatlinburg, Tennessee",
    distance: "2 hours away",
    dates: "May 1–6",
    price: 185,
    rating: 4.92,
    reviewCount: 47,
    images: [
      "https://placehold.co/600x400/e2e8f0/475569?text=Cabin+1",
      "https://placehold.co/600x400/dbeafe/1e40af?text=Interior",
      "https://placehold.co/600x400/f1f5f9/64748b?text=View",
    ],
    trustScore: 92,
    connectionLabel: "Friend of Sarah M.",
    isSuperhost: true,
    category: "cabins",
  },
  {
    id: "2",
    title: "Modern Loft in Downtown Nashville",
    location: "Nashville, Tennessee",
    distance: "45 min away",
    dates: "Apr 20–25",
    price: 145,
    rating: 4.87,
    reviewCount: 83,
    images: [
      "https://placehold.co/600x400/dbeafe/1e40af?text=Loft+1",
      "https://placehold.co/600x400/e2e8f0/475569?text=Kitchen",
      "https://placehold.co/600x400/f1f5f9/64748b?text=Bedroom",
    ],
    trustScore: 88,
    connectionLabel: "2nd degree connection",
    isSuperhost: false,
    category: "trending",
  },
  {
    id: "3",
    title: "Beachfront Cottage with Ocean Views",
    location: "Destin, Florida",
    distance: "6 hours away",
    dates: "Jun 10–15",
    price: 275,
    rating: 4.95,
    reviewCount: 124,
    images: [
      "https://placehold.co/600x400/bfdbfe/1d4ed8?text=Beach+1",
      "https://placehold.co/600x400/dbeafe/1e40af?text=Patio",
      "https://placehold.co/600x400/e2e8f0/475569?text=Sunset",
    ],
    trustScore: 96,
    connectionLabel: "Friend of Mike T.",
    isSuperhost: true,
    category: "beachfront",
  },
  {
    id: "4",
    title: "Rustic Farmhouse on 10 Acres",
    location: "Blue Ridge, Georgia",
    distance: "3 hours away",
    dates: "May 15–20",
    price: 165,
    rating: 4.78,
    reviewCount: 31,
    images: [
      "https://placehold.co/600x400/d1fae5/059669?text=Farm+1",
      "https://placehold.co/600x400/ecfdf5/047857?text=Barn",
      "https://placehold.co/600x400/f1f5f9/64748b?text=Field",
    ],
    trustScore: 74,
    connectionLabel: null,
    isSuperhost: false,
    category: "countryside",
  },
  {
    id: "5",
    title: "Luxury Treehouse Retreat",
    location: "Asheville, North Carolina",
    distance: "4 hours away",
    dates: "Jul 1–6",
    price: 320,
    rating: 4.98,
    reviewCount: 67,
    images: [
      "https://placehold.co/600x400/fef3c7/d97706?text=Treehouse",
      "https://placehold.co/600x400/fffbeb/b45309?text=Deck",
      "https://placehold.co/600x400/f1f5f9/64748b?text=Forest",
    ],
    trustScore: 98,
    connectionLabel: "Friend of Anna K.",
    isSuperhost: true,
    category: "treehouses",
  },
  {
    id: "6",
    title: "Stylish Studio near the Arts District",
    location: "Savannah, Georgia",
    distance: "5 hours away",
    dates: "May 5–10",
    price: 110,
    rating: 4.83,
    reviewCount: 55,
    images: [
      "https://placehold.co/600x400/ede9fe/7c3aed?text=Studio",
      "https://placehold.co/600x400/f5f3ff/6d28d9?text=Living",
      "https://placehold.co/600x400/f1f5f9/64748b?text=Art",
    ],
    trustScore: 82,
    connectionLabel: "2nd degree connection",
    isSuperhost: false,
    category: "trending",
  },
  {
    id: "7",
    title: "Lakefront A-Frame with Dock",
    location: "Lake Lure, North Carolina",
    distance: "3.5 hours away",
    dates: "Jun 20–25",
    price: 240,
    rating: 4.91,
    reviewCount: 39,
    images: [
      "https://placehold.co/600x400/bfdbfe/1d4ed8?text=Lake+1",
      "https://placehold.co/600x400/dbeafe/1e40af?text=Dock",
      "https://placehold.co/600x400/e2e8f0/475569?text=A-Frame",
    ],
    trustScore: 90,
    connectionLabel: "Friend of James R.",
    isSuperhost: true,
    category: "lakefront",
  },
  {
    id: "8",
    title: "Charming Victorian in Historic District",
    location: "Charleston, South Carolina",
    distance: "5 hours away",
    dates: "Apr 25–30",
    price: 195,
    rating: 4.86,
    reviewCount: 72,
    images: [
      "https://placehold.co/600x400/fce7f3/be185d?text=Victorian",
      "https://placehold.co/600x400/fdf2f8/9d174d?text=Parlor",
      "https://placehold.co/600x400/f1f5f9/64748b?text=Garden",
    ],
    trustScore: 85,
    connectionLabel: "Friend of Lisa P.",
    isSuperhost: false,
    category: "amazing-views",
  },
  {
    id: "9",
    title: "Off-Grid Tiny Home in the Woods",
    location: "Pigeon Forge, Tennessee",
    distance: "2.5 hours away",
    dates: "May 20–25",
    price: 95,
    rating: 4.79,
    reviewCount: 28,
    images: [
      "https://placehold.co/600x400/d1fae5/059669?text=Tiny+Home",
      "https://placehold.co/600x400/ecfdf5/047857?text=Inside",
      "https://placehold.co/600x400/f1f5f9/64748b?text=Woods",
    ],
    trustScore: 70,
    connectionLabel: null,
    isSuperhost: false,
    category: "tiny-homes",
  },
  {
    id: "10",
    title: "Penthouse with Skyline Views",
    location: "Atlanta, Georgia",
    distance: "1 hour away",
    dates: "Jun 5–10",
    price: 350,
    rating: 4.94,
    reviewCount: 91,
    images: [
      "https://placehold.co/600x400/dbeafe/1e40af?text=Penthouse",
      "https://placehold.co/600x400/bfdbfe/1d4ed8?text=Skyline",
      "https://placehold.co/600x400/f1f5f9/64748b?text=Rooftop",
    ],
    trustScore: 94,
    connectionLabel: "Friend of David W.",
    isSuperhost: true,
    category: "amazing-views",
  },
  {
    id: "11",
    title: "Secluded Yurt with Hot Tub",
    location: "Helen, Georgia",
    distance: "2 hours away",
    dates: "Jul 10–15",
    price: 175,
    rating: 4.88,
    reviewCount: 44,
    images: [
      "https://placehold.co/600x400/fef3c7/d97706?text=Yurt",
      "https://placehold.co/600x400/fffbeb/b45309?text=Hot+Tub",
      "https://placehold.co/600x400/f1f5f9/64748b?text=Mountain",
    ],
    trustScore: 86,
    connectionLabel: "2nd degree connection",
    isSuperhost: false,
    category: "cabins",
  },
  {
    id: "12",
    title: "Renovated Barn with Pool",
    location: "Dahlonega, Georgia",
    distance: "1.5 hours away",
    dates: "May 25–30",
    price: 225,
    rating: 4.9,
    reviewCount: 36,
    images: [
      "https://placehold.co/600x400/d1fae5/059669?text=Barn",
      "https://placehold.co/600x400/ecfdf5/047857?text=Pool",
      "https://placehold.co/600x400/f1f5f9/64748b?text=Interior",
    ],
    trustScore: 88,
    connectionLabel: "Friend of Tom B.",
    isSuperhost: true,
    category: "countryside",
  },
];

export const categories = [
  { slug: "trending", label: "Trending", icon: "Flame" },
  { slug: "beachfront", label: "Beachfront", icon: "Waves" },
  { slug: "cabins", label: "Cabins", icon: "TreePine" },
  { slug: "amazing-views", label: "Amazing views", icon: "Mountain" },
  { slug: "lakefront", label: "Lakefront", icon: "Sailboat" },
  { slug: "countryside", label: "Countryside", icon: "Wheat" },
  { slug: "tiny-homes", label: "Tiny homes", icon: "Home" },
  { slug: "treehouses", label: "Treehouses", icon: "TreeDeciduous" },
  { slug: "luxe", label: "Luxe", icon: "Crown" },
  { slug: "new", label: "New", icon: "Sparkles" },
] as const;

export type Category = (typeof categories)[number]["slug"];
