import type { ListingCardProps } from "@/components/listing-card";

const PLACEHOLDER = "https://placehold.co/800x600/E5E7EB/9CA3AF?text=Listing";
const PLACEHOLDER_2 = "https://placehold.co/800x600/DBEAFE/2563EB?text=Photo+2";
const PLACEHOLDER_3 = "https://placehold.co/800x600/D1FAE5/059669?text=Photo+3";

export const MOCK_LISTINGS: ListingCardProps[] = [
  {
    id: "1",
    title: "Cozy downtown loft with skyline views",
    location: "Austin, Texas",
    images: [PLACEHOLDER, PLACEHOLDER_2, PLACEHOLDER_3],
    pricePerNight: 145,
    rating: 4.92,
    reviewCount: 47,
    isFavorited: false,
    trustScore: 87,
    connectionLabel: "Via Sarah M.",
    category: "apartments",
  },
  {
    id: "2",
    title: "Charming craftsman bungalow near the park",
    location: "Portland, Oregon",
    images: [PLACEHOLDER_2, PLACEHOLDER, PLACEHOLDER_3],
    pricePerNight: 110,
    rating: 4.85,
    reviewCount: 32,
    isFavorited: true,
    trustScore: 72,
    connectionLabel: "2nd degree",
    category: "houses",
  },
  {
    id: "3",
    title: "Modern studio with pool access",
    location: "Miami, Florida",
    images: [PLACEHOLDER_3, PLACEHOLDER_2],
    pricePerNight: 95,
    rating: 4.7,
    reviewCount: 18,
    isFavorited: false,
    trustScore: 54,
    connectionLabel: null,
    category: "pool",
  },
  {
    id: "4",
    title: "Waterfront cabin with private dock",
    location: "Lake Tahoe, California",
    images: [PLACEHOLDER, PLACEHOLDER_3],
    pricePerNight: 220,
    rating: 4.98,
    reviewCount: 63,
    isFavorited: false,
    trustScore: 95,
    connectionLabel: "Via James K.",
    category: "waterfront",
  },
  {
    id: "5",
    title: "Sunny private room in brownstone",
    location: "Brooklyn, New York",
    images: [PLACEHOLDER_2, PLACEHOLDER],
    pricePerNight: 75,
    rating: 4.6,
    reviewCount: 12,
    isFavorited: false,
    trustScore: 41,
    connectionLabel: "3rd degree",
    category: "rooms",
  },
  {
    id: "6",
    title: "Converted treehouse in the woods",
    location: "Asheville, North Carolina",
    images: [PLACEHOLDER_3, PLACEHOLDER, PLACEHOLDER_2],
    pricePerNight: 180,
    rating: 5.0,
    reviewCount: 28,
    isFavorited: true,
    trustScore: 88,
    connectionLabel: "Via Emma R.",
    category: "unique",
  },
  {
    id: "7",
    title: "Pet-friendly ranch house with yard",
    location: "Nashville, Tennessee",
    images: [PLACEHOLDER, PLACEHOLDER_2],
    pricePerNight: 130,
    rating: 4.78,
    reviewCount: 22,
    isFavorited: false,
    trustScore: 66,
    connectionLabel: null,
    category: "pet-friendly",
  },
  {
    id: "8",
    title: "High-rise apartment in downtown",
    location: "Chicago, Illinois",
    images: [PLACEHOLDER_2, PLACEHOLDER_3, PLACEHOLDER],
    pricePerNight: 165,
    rating: 4.88,
    reviewCount: 41,
    isFavorited: false,
    trustScore: 79,
    connectionLabel: "Via David L.",
    category: "city",
  },
  {
    id: "9",
    title: "Quiet suburban home near trails",
    location: "Boulder, Colorado",
    images: [PLACEHOLDER, PLACEHOLDER_3],
    pricePerNight: 125,
    rating: 4.82,
    reviewCount: 35,
    isFavorited: false,
    trustScore: 71,
    connectionLabel: "2nd degree",
    category: "suburban",
  },
  {
    id: "10",
    title: "Beach cottage steps from the shore",
    location: "San Diego, California",
    images: [PLACEHOLDER_3, PLACEHOLDER_2, PLACEHOLDER],
    pricePerNight: 195,
    rating: 4.95,
    reviewCount: 56,
    isFavorited: false,
    trustScore: 92,
    connectionLabel: "Via Lisa P.",
    category: "waterfront",
  },
  {
    id: "11",
    title: "Artist studio loft with gallery space",
    location: "Santa Fe, New Mexico",
    images: [PLACEHOLDER_2],
    pricePerNight: 105,
    rating: 4.73,
    reviewCount: 15,
    isFavorited: false,
    trustScore: 58,
    connectionLabel: null,
    category: "apartments",
  },
  {
    id: "12",
    title: "Family farmhouse with garden",
    location: "Burlington, Vermont",
    images: [PLACEHOLDER, PLACEHOLDER_2, PLACEHOLDER_3],
    pricePerNight: 155,
    rating: 4.9,
    reviewCount: 44,
    isFavorited: true,
    trustScore: 84,
    connectionLabel: "Via Mark T.",
    category: "houses",
  },
];
